cull CI for now

diff --git a/.github/workflows/on-push.yml b/.github/workflows/on-push.yml
--- a/.github/workflows/on-push.yml
+++ b/.github/workflows/on-push.yml
@@ -10,45 +10,45 @@ jobs:
 
 # =============================================================================
 
-  PreCommit:
-    runs-on: ubuntu-latest
+  # PreCommit:
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - name: Extract branch name
-        run: |
-          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
-        id: extract_branch
-      - name: Test branch name
-        run: |
-          echo ${{ steps.extract_branch.outputs.branch }}
-      - uses: actions/checkout@v2
-      - name: Set up Python 3.8
-        uses: actions/setup-python@v1
-        with:
-          python-version: 3.8
+  #   steps:
+  #     - name: Extract branch name
+  #       run: |
+  #         echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
+  #       id: extract_branch
+  #     - name: Test branch name
+  #       run: |
+  #         echo ${{ steps.extract_branch.outputs.branch }}
+  #     - uses: actions/checkout@v2
+  #     - name: Set up Python 3.8
+  #       uses: actions/setup-python@v1
+  #       with:
+  #         python-version: 3.8
 
-      - uses: actions/cache@v2
-        with:
-          path: ~/.cache/pre-commit
-          key: pre-commit-cache
+  #     - uses: actions/cache@v2
+  #       with:
+  #         path: ~/.cache/pre-commit
+  #         key: pre-commit-cache
 
-      - name: Run Pre-Commit
-        run: |
-          pip install pre-commit
-          pre-commit run --all-files
-      - name: Fix any issues
-        if: failure()
-        run: |
-          git config --local user.email "pre-commit-bot@pymedphys.com"
-          git config --local user.name "PyMedPhys Pre-Commit Bot"
-          git commit -m "Fix pre-commit failures" -a
-          exit 1
-      - name: Push changes
-        if: failure()
-        uses: ad-m/github-push-action@02b0b75
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          branch: ${{ steps.extract_branch.outputs.branch }}
+  #     - name: Run Pre-Commit
+  #       run: |
+  #         pip install pre-commit
+  #         pre-commit run --all-files
+  #     - name: Fix any issues
+  #       if: failure()
+  #       run: |
+  #         git config --local user.email "pre-commit-bot@pymedphys.com"
+  #         git config --local user.name "PyMedPhys Pre-Commit Bot"
+  #         git commit -m "Fix pre-commit failures" -a
+  #         exit 1
+  #     - name: Push changes
+  #       if: failure()
+  #       uses: ad-m/github-push-action@02b0b75
+  #       with:
+  #         github_token: ${{ secrets.GITHUB_TOKEN }}
+  #         branch: ${{ steps.extract_branch.outputs.branch }}
 
 # =============================================================================
 
@@ -56,9 +56,12 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        os: ['ubuntu', 'macos', 'windows']
-        task: ['tests', 'docs', 'stackoverflow', 'updates', 'cypress', 'slow']
+        os: ['windows']  # ['ubuntu', 'macos', 'windows']
+        task: ['binary']  # ['tests', 'docs', 'stackoverflow', 'updates', 'cypress', 'slow']
         exclude:
+          - os: 'ubuntu'
+            task: 'binary'
+
           - os: 'windows'
             task: 'stackoverflow'
           - os: 'windows'
@@ -76,6 +79,8 @@ jobs:
             task: 'cypress'
           - os: 'macos'
             task: 'slow'
+          - os: 'macos'
+            task: 'binary'
 
         include:
           - os: 'ubuntu'
