change to ubuntu-latest, ignore other CI for now

diff --git a/.github/workflows/on-push.yml b/.github/workflows/on-push.yml
--- a/.github/workflows/on-push.yml
+++ b/.github/workflows/on-push.yml
@@ -1,340 +1,340 @@
-name: PullRequest
-
-on:
-  push:
-    branches:
-      - main
-  pull_request:
-
-jobs:
-
-# =============================================================================
-
-  PreCommit:
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Extract branch name
-        run: |
-          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
-        id: extract_branch
-      - name: Test branch name
-        run: |
-          echo ${{ steps.extract_branch.outputs.branch }}
-      - uses: actions/checkout@v2
-      - name: Set up Python 3.8
-        uses: actions/setup-python@v1
-        with:
-          python-version: 3.8
-
-      - uses: actions/cache@v2
-        with:
-          path: ~/.cache/pre-commit
-          key: pre-commit-cache
-
-      - name: Run Pre-Commit
-        run: |
-          pip install pre-commit
-          pre-commit run --all-files
-      - name: Fix any issues
-        if: failure()
-        run: |
-          git config --local user.email "pre-commit-bot@pymedphys.com"
-          git config --local user.name "PyMedPhys Pre-Commit Bot"
-          git commit -m "Fix pre-commit failures" -a
-          exit 1
-      - name: Push changes
-        if: failure()
-        uses: ad-m/github-push-action@02b0b75
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          branch: ${{ steps.extract_branch.outputs.branch }}
-
-# =============================================================================
-
-  Tests:
-    strategy:
-      fail-fast: false
-      matrix:
-        os: ['ubuntu', 'macos', 'windows']
-        task: ['tests', 'docs', 'stackoverflow', 'updates', 'cypress', 'slow']
-        exclude:
-          - os: 'windows'
-            task: 'stackoverflow'
-          - os: 'windows'
-            task: 'updates'
-          - os: 'windows'
-            task: 'cypress'
-          - os: 'windows'
-            task: 'slow'
-
-          - os: 'macos'
-            task: 'stackoverflow'
-          - os: 'macos'
-            task: 'updates'
-          - os: 'macos'
-            task: 'cypress'
-          - os: 'macos'
-            task: 'slow'
-
-        include:
-          - os: 'ubuntu'
-            python-version: 3.8
-          - os: 'windows'
-            python-version: 3.7
-          - os: 'macos'
-            python-version: 3.8
-
-    runs-on: ${{ matrix.os }}-latest
-
-    steps:
-    - uses: actions/checkout@v2
-
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v2
-      with:
-        python-version: ${{ matrix.python-version }}
-
-    - name: Get full Python version
-      id: full-python-version
-      shell: bash
-      run: |
-        echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")
-
-# Set up pip
-
-    - name: Get pip cache dir
-      id: pip-cache
-      run: |
-        python -m pip install -U pip # to ensure version > 20 to have cache dir
-        echo "::set-output name=dir::$(pip cache dir)"
-
-    - name: Pip Cache
-      uses: actions/cache@v2
-      with:
-        path: ${{ steps.pip-cache.outputs.dir }}
-        key: pip-${{ matrix.task }}-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}
-
-# Upgrade pip and setuptools, and install poetry
-
-    - name: Upgrade pip and setuptools
-      run: |
-        pip install --upgrade pip setuptools
-
-    - name: Install Poetry on *Nix
-      if: matrix.os != 'windows'
-      uses: dschep/install-poetry-action@v1.3
-      with:
-        version: 1.1.4
-        create_virtualenvs: true
-
-    # Currently python subprocesses in Windows don't appear to appropriately
-    # fork under the poetry virtual environment for version 1.1.4
-    - name: Install Poetry on Windows
-      if: matrix.os == 'windows'
-      uses: dschep/install-poetry-action@v1.3
-      with:
-        version: 1.0.9
-        create_virtualenvs: true
-
-# No import and run CLI with no dependencies
-
-    - name: Build wheel
-      if: matrix.task == 'tests'
-      run: |
-        poetry build --format wheel
-
-    - name: Install wheel
-      if: matrix.task == 'tests' && matrix.os == 'windows'
-      run: |
-        python -m pip install (Get-Item .\dist\*.whl)
-
-    - name: Install wheel
-      if: matrix.task == 'tests' && matrix.os != 'windows'
-      run: |
-        python -m pip install ./dist/*.whl
-
-    - name: Run clean tests
-      if: matrix.task == 'tests'
-      run: |
-        pymedphys --help
-        python -c "import pymedphys"
-        python -c "import pymedphys.beta"
-        python -c "import pymedphys.experimental"
-
-    # Remove confusion for tests down the line
-    - name: Remove base install of pymedphys
-      if: matrix.task == 'tests'
-      run: |
-        pip uninstall -y pymedphys
-
-
-# Set up Poetry
-
-    - name: Configure poetry
-      run: |
-        poetry config virtualenvs.in-project true
-
-    - name: Poetry Cache
-      uses: actions/cache@v2
-      id: poetry-cache
-      with:
-        path: .venv
-        key: venv-${{ matrix.task }}-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}
-
-    - name: Ensure cache is healthy
-      if: steps.poetry-cache.outputs.cache-hit == 'true'
-      shell: bash
-      run: |
-        poetry run pip --version >/dev/null 2>&1 || rm -rf .venv
-
-# System installs
-
-    - name: Install FreeTDS on MacOS
-      if: matrix.os == 'macos'
-      run: |
-        brew install freetds
-
-    - name: Install Pandoc on Ubuntu
-      if: ( matrix.task == 'docs' || matrix.task == 'updates' ) && matrix.os == 'ubuntu'
-      run: |
-        sudo apt-get install -y pandoc
-
-    - name: Install Pandoc on MacOS
-      if: matrix.task == 'docs' && matrix.os == 'macos'
-      run: |
-        brew install pandoc
-
-    - name: Install Pandoc on Windows
-      if: matrix.task == 'docs' && matrix.os == 'windows'
-      run: |
-        choco install pandoc
-
-## Plain install
-
-    - name: Install a plain environment
-      if: matrix.task == 'stackoverflow'
-      run: |
-        poetry install -E user
-
+# name: PullRequest
+
+# on:
+#   push:
+#     branches:
+#       - main
+#   pull_request:
+
+# jobs:
+
+# # =============================================================================
+
+#   PreCommit:
+#     runs-on: ubuntu-latest
+
+#     steps:
+#       - name: Extract branch name
+#         run: |
+#           echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
+#         id: extract_branch
+#       - name: Test branch name
+#         run: |
+#           echo ${{ steps.extract_branch.outputs.branch }}
+#       - uses: actions/checkout@v2
+#       - name: Set up Python 3.8
+#         uses: actions/setup-python@v1
+#         with:
+#           python-version: 3.8
+
+#       - uses: actions/cache@v2
+#         with:
+#           path: ~/.cache/pre-commit
+#           key: pre-commit-cache
+
+#       - name: Run Pre-Commit
+#         run: |
+#           pip install pre-commit
+#           pre-commit run --all-files
+#       - name: Fix any issues
+#         if: failure()
+#         run: |
+#           git config --local user.email "pre-commit-bot@pymedphys.com"
+#           git config --local user.name "PyMedPhys Pre-Commit Bot"
+#           git commit -m "Fix pre-commit failures" -a
+#           exit 1
+#       - name: Push changes
+#         if: failure()
+#         uses: ad-m/github-push-action@02b0b75
+#         with:
+#           github_token: ${{ secrets.GITHUB_TOKEN }}
+#           branch: ${{ steps.extract_branch.outputs.branch }}
+
+# # =============================================================================
+
+#   Tests:
+#     strategy:
+#       fail-fast: false
+#       matrix:
+#         os: ['ubuntu', 'macos', 'windows']
+#         task: ['tests', 'docs', 'stackoverflow', 'updates', 'cypress', 'slow']
+#         exclude:
+#           - os: 'windows'
+#             task: 'stackoverflow'
+#           - os: 'windows'
+#             task: 'updates'
+#           - os: 'windows'
+#             task: 'cypress'
+#           - os: 'windows'
+#             task: 'slow'
+
+#           - os: 'macos'
+#             task: 'stackoverflow'
+#           - os: 'macos'
+#             task: 'updates'
+#           - os: 'macos'
+#             task: 'cypress'
+#           - os: 'macos'
+#             task: 'slow'
+
+#         include:
+#           - os: 'ubuntu'
+#             python-version: 3.8
+#           - os: 'windows'
+#             python-version: 3.7
+#           - os: 'macos'
+#             python-version: 3.8
+
+#     runs-on: ${{ matrix.os }}-latest
+
+#     steps:
+#     - uses: actions/checkout@v2
+
+#     - name: Set up Python ${{ matrix.python-version }}
+#       uses: actions/setup-python@v2
+#       with:
+#         python-version: ${{ matrix.python-version }}
+
+#     - name: Get full Python version
+#       id: full-python-version
+#       shell: bash
+#       run: |
+#         echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")
+
+# # Set up pip
+
+#     - name: Get pip cache dir
+#       id: pip-cache
+#       run: |
+#         python -m pip install -U pip # to ensure version > 20 to have cache dir
+#         echo "::set-output name=dir::$(pip cache dir)"
+
+#     - name: Pip Cache
+#       uses: actions/cache@v2
+#       with:
+#         path: ${{ steps.pip-cache.outputs.dir }}
+#         key: pip-${{ matrix.task }}-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}
+
+# # Upgrade pip and setuptools, and install poetry
+
+#     - name: Upgrade pip and setuptools
+#       run: |
+#         pip install --upgrade pip setuptools
+
+#     - name: Install Poetry on *Nix
+#       if: matrix.os != 'windows'
+#       uses: dschep/install-poetry-action@v1.3
+#       with:
+#         version: 1.1.4
+#         create_virtualenvs: true
+
+#     # Currently python subprocesses in Windows don't appear to appropriately
+#     # fork under the poetry virtual environment for version 1.1.4
+#     - name: Install Poetry on Windows
+#       if: matrix.os == 'windows'
+#       uses: dschep/install-poetry-action@v1.3
+#       with:
+#         version: 1.0.9
+#         create_virtualenvs: true
+
+# # No import and run CLI with no dependencies
+
+#     - name: Build wheel
+#       if: matrix.task == 'tests'
+#       run: |
+#         poetry build --format wheel
+
+#     - name: Install wheel
+#       if: matrix.task == 'tests' && matrix.os == 'windows'
+#       run: |
+#         python -m pip install (Get-Item .\dist\*.whl)
+
+#     - name: Install wheel
+#       if: matrix.task == 'tests' && matrix.os != 'windows'
+#       run: |
+#         python -m pip install ./dist/*.whl
+
+#     - name: Run clean tests
+#       if: matrix.task == 'tests'
+#       run: |
+#         pymedphys --help
+#         python -c "import pymedphys"
+#         python -c "import pymedphys.beta"
+#         python -c "import pymedphys.experimental"
+
+#     # Remove confusion for tests down the line
+#     - name: Remove base install of pymedphys
+#       if: matrix.task == 'tests'
+#       run: |
+#         pip uninstall -y pymedphys
+
+
+# # Set up Poetry
+
+#     - name: Configure poetry
+#       run: |
+#         poetry config virtualenvs.in-project true
+
+#     - name: Poetry Cache
+#       uses: actions/cache@v2
+#       id: poetry-cache
+#       with:
+#         path: .venv
+#         key: venv-${{ matrix.task }}-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}
+
+#     - name: Ensure cache is healthy
+#       if: steps.poetry-cache.outputs.cache-hit == 'true'
+#       shell: bash
+#       run: |
+#         poetry run pip --version >/dev/null 2>&1 || rm -rf .venv
+
+# # System installs
+
+#     - name: Install FreeTDS on MacOS
+#       if: matrix.os == 'macos'
+#       run: |
+#         brew install freetds
+
+#     - name: Install Pandoc on Ubuntu
+#       if: ( matrix.task == 'docs' || matrix.task == 'updates' ) && matrix.os == 'ubuntu'
+#       run: |
+#         sudo apt-get install -y pandoc
+
+#     - name: Install Pandoc on MacOS
+#       if: matrix.task == 'docs' && matrix.os == 'macos'
+#       run: |
+#         brew install pandoc
+
+#     - name: Install Pandoc on Windows
+#       if: matrix.task == 'docs' && matrix.os == 'windows'
+#       run: |
+#         choco install pandoc
+
+# ## Plain install
+
+#     - name: Install a plain environment
+#       if: matrix.task == 'stackoverflow'
+#       run: |
+#         poetry install -E user
+
 
-## Install with Documentation Environment
-
-    - name: Install a docs environment
-      if: matrix.task == 'docs'
-      run: |
-        poetry install -E user -E docs
+# ## Install with Documentation Environment
+
+#     - name: Install a docs environment
+#       if: matrix.task == 'docs'
+#       run: |
+#         poetry install -E user -E docs
 
-## Install with Tests Environment
+# ## Install with Tests Environment
 
-    - name: Install a tests environment
-      if: matrix.task == 'tests' || matrix.task == 'cypress' || matrix.task == 'slow'
-      run: |
-        poetry install -E user -E tests
+#     - name: Install a tests environment
+#       if: matrix.task == 'tests' || matrix.task == 'cypress' || matrix.task == 'slow'
+#       run: |
+#         poetry install -E user -E tests
 
-## Install Extra Packages for Doctests
+# ## Install Extra Packages for Doctests
 
-    - name: Install extra packages for doctests
-      if: matrix.os == 'ubuntu' && matrix.task == 'tests'
-      run: |
-        poetry install -E user -E doctests
+#     - name: Install extra packages for doctests
+#       if: matrix.os == 'ubuntu' && matrix.task == 'tests'
+#       run: |
+#         poetry install -E user -E doctests
 
-## Update all packages and then install with tests environment
+# ## Update all packages and then install with tests environment
 
-    - name: Update all packages then install with tests, user and doctests environment
-      if: matrix.task == 'updates'
-      run: |
-        poetry install -E user -E tests -E docs -E doctests
-        poetry update
-        poetry install -E user -E tests -E docs -E doctests
+#     - name: Update all packages then install with tests, user and doctests environment
+#       if: matrix.task == 'updates'
+#       run: |
+#         poetry install -E user -E tests -E docs -E doctests
+#         poetry update
+#         poetry install -E user -E tests -E docs -E doctests
 
-# Download all data for consistent cache
+# # Download all data for consistent cache
 
-    - name: Get PyMedPhys cache directory
-      id: pymedphys-cache-location
-      run: |
-        echo "::set-output name=dir::$(poetry run python -c 'import pymedphys._config as cf; print(str(cf.get_config_dir()))')"
+#     - name: Get PyMedPhys cache directory
+#       id: pymedphys-cache-location
+#       run: |
+#         echo "::set-output name=dir::$(poetry run python -c 'import pymedphys._config as cf; print(str(cf.get_config_dir()))')"
 
-    - name: PyMedPhys Cache
-      id: pymedphys-cache
-      uses: actions/cache@v2
-      with:
-        path: ${{ steps.pymedphys-cache-location.outputs.dir }}
-        key: pymedphys-${{ matrix.task }}-${{ runner.os }}-${{ hashFiles('**/hashes.json') }}
+#     - name: PyMedPhys Cache
+#       id: pymedphys-cache
+#       uses: actions/cache@v2
+#       with:
+#         path: ${{ steps.pymedphys-cache-location.outputs.dir }}
+#         key: pymedphys-${{ matrix.task }}-${{ runner.os }}-${{ hashFiles('**/hashes.json') }}
 
 
-# TESTS
+# # TESTS
 
-## Propagate
+# ## Propagate
 
-    - name: See if propagate is needed
-      if: matrix.os == 'ubuntu' && matrix.task == 'tests'
-      run: |
-        poetry run pymedphys dev propagate
+#     - name: See if propagate is needed
+#       if: matrix.os == 'ubuntu' && matrix.task == 'tests'
+#       run: |
+#         poetry run pymedphys dev propagate
 
-        git config --local user.email "propagate-bot@pymedphys.com"
-        git config --local user.name "PyMedPhys Propagate Bot"
-        git add poetry.lock
-        git commit -m "dummy commit"
+#         git config --local user.email "propagate-bot@pymedphys.com"
+#         git config --local user.name "PyMedPhys Propagate Bot"
+#         git add poetry.lock
+#         git commit -m "dummy commit"
 
-        git status
-        git diff-index --quiet HEAD --
+#         git status
+#         git diff-index --quiet HEAD --
 
-## Pytest
+# ## Pytest
 
-    - name: Run basic pytest tests
-      if: matrix.task == 'tests' || matrix.task == 'updates'
-      run: |
-        poetry run pymedphys dev tests -v
+#     - name: Run basic pytest tests
+#       if: matrix.task == 'tests' || matrix.task == 'updates'
+#       run: |
+#         poetry run pymedphys dev tests -v
 
-## Doctest
+# ## Doctest
 
-    - name: Run doctest tests
-      if: matrix.os == 'ubuntu' && matrix.task == 'tests'
-      run: |
-        poetry run pymedphys dev tests -v --doctest-modules
+#     - name: Run doctest tests
+#       if: matrix.os == 'ubuntu' && matrix.task == 'tests'
+#       run: |
+#         poetry run pymedphys dev tests -v --doctest-modules
 
-## Pylint
+# ## Pylint
 
-    - name: Run pylint tests
-      if: matrix.os == 'ubuntu' && ( matrix.task == 'tests' || matrix.task == 'updates' )
-      run: |
-        poetry run pymedphys dev tests --pylint --pylint-jobs=1
+#     - name: Run pylint tests
+#       if: matrix.os == 'ubuntu' && ( matrix.task == 'tests' || matrix.task == 'updates' )
+#       run: |
+#         poetry run pymedphys dev tests --pylint --pylint-jobs=1
 
-## Slow
+# ## Slow
 
-    - name: Run slow tests
-      if: matrix.task == 'slow'
-      run: |
-        poetry run pymedphys dev tests -v --slow
+#     - name: Run slow tests
+#       if: matrix.task == 'slow'
+#       run: |
+#         poetry run pymedphys dev tests -v --slow
 
-## Docs
+# ## Docs
 
-    - name: Build docs
-      if: matrix.task == 'docs' || matrix.task == 'updates'
-      run: |
-        poetry run pymedphys dev docs
+#     - name: Build docs
+#       if: matrix.task == 'docs' || matrix.task == 'updates'
+#       run: |
+#         poetry run pymedphys dev docs
 
-## Stackoverflow
+# ## Stackoverflow
 
-    - name: Run stackoverflow example(s)
-      if: matrix.task == 'stackoverflow'
-      run: |
-        poetry run python ./examples/stackoverflow/gamma.py
+#     - name: Run stackoverflow example(s)
+#       if: matrix.task == 'stackoverflow'
+#       run: |
+#         poetry run python ./examples/stackoverflow/gamma.py
 
 
-## Cypress
+# ## Cypress
 
-    - uses: actions/setup-node@v1
-      if: matrix.task == 'cypress'
+#     - uses: actions/setup-node@v1
+#       if: matrix.task == 'cypress'
 
-    - name: Run Cypress tests
-      if: matrix.task == 'cypress'
-      run: |
-        poetry run pymedphys dev tests -v -s --cypress
+#     - name: Run Cypress tests
+#       if: matrix.task == 'cypress'
+#       run: |
+#         poetry run pymedphys dev tests -v -s --cypress
 
-    - uses: actions/upload-artifact@v2
-      if: failure() && matrix.task == 'cypress'
-      with:
-        name: cypress-videos
-        path: pymedphys/tests/e2e/cypress/videos
+#     - uses: actions/upload-artifact@v2
+#       if: failure() && matrix.task == 'cypress'
+#       with:
+#         name: cypress-videos
+#         path: pymedphys/tests/e2e/cypress/videos
